### ISSUE TITLE
Update to 16?

### ISSUE THREAD

**Issue by dereuromark** [alt3/cakebox#71]
```
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-24-generic x86_64)

...

New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

```

Any way to have 16 by default already?

**Comment by bravo-kernel** [comment]
That would require generating a new box using https://github.com/alt3/cakebox-builder. I have no short term plans so a manual upgrade would be the quickest route atm.

**Comment by dereuromark** [comment]
For security reasons it soon becomes vital that the box ships with current defaults and mainly also php7.0+ (better 7.1) by default.

**Comment by josegonzalez** [comment]
This is used for local development. What security reasons are there around upgrading this now?

**Comment by bravo-kernel** [comment]
In all honesty [this PR](https://github.com/alt3/cakebox/pull/75 ) could hypothetically introduce security issues but IMHO those are far-fetched as the intended usage is for (really local) LAN only and hold no ground as a must-upgrade-now argument. Besides that I see:

- no short-term upgrade of the box-version due to the complex [Chef kitchen build](https://github.com/alt3/cakebox-builder) which will require serious time (feel free to try it yourself)
- no need to implement PHP7, one is free to install it themselves on the box (using customization script in YAML) 

Lastly, if PHP gets touched it will no longer be single-version oriented but instead implement one of the many solutions out there supporting multiple PHP versions (the single design error we made when thinking up the box).

**Comment by bravo-kernel** [comment]
One more thing to hopefully prevent this from sounding to negative/unwilling. While adding the backup functionality I thought about adding a (new) bash upgrade script instead of creating a new box. 
IMO this would be the desired route since it would mean existing cakebox could keep using their existing boxes.

E.g. executed after some boolean switch in the yaml (e.g. `autoUpdate`). This would then also be usable for  upgrading/replacing PHP, updating sql, security patches, etc.

**Comment by bravo-kernel** [comment]
I just managed to do an in-box upgrade so this feature is surely coming now, PHP 7.1 included.

![afbeelding](https://cloud.githubusercontent.com/assets/230500/24081442/bd71cd82-0cb3-11e7-8657-1f09d140f6de.png)

I will need some time to integrate this with cakebox provisioning but these are the steps if you want to do the upgrade manually;

```bash
## Check for current release, exit if already 16
lsb_release -a

## Install package containing add-apt-repository command
sudo apt-get install software-properties-common --assume-yes

## Replace depracted PHP 5.5 source with ppa PHP 7.1 source
sudo rm /etc/apt/sources.list.d/php5-5.6.list
sudo add-apt-repository ppa:ondrej/php -y

## Remove deprecated ppa source for Percona
sudo rm /etc/apt/sources.list.d/percona.list

## Refresh the local repository list (should no longer give any errors)
sudo apt-get update --assume-yes

## === snapshot =====
sudo apt-get install linux-headers-4.4.0-63-generic --assume-yes
sudo apt-get install linux-image-4.4.0-63-generic --assume-yes
sudo apt-get install linux-image-extra-4.4.0-63-generic --assume-yes

## Remove this directory as it will prevent do-release-upgrade building the new kernel image
sudo rm /etc/udev/rules.d/70-persistent-net.rules/ -rf

## Run dist-upgrade to upgrade installed packages and build new kernel
## image as preparation for major version upgrade (--confold to prefer
## keeping existing confs to not break e.g. IP configuration)
sudo DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' dist-upgrade

## ============================================
## FYI software has already been upgraded here:
## 
## lsb_release -a	=> 16.04.2 LTS
## php -v		=> php 7.1.3
## hhvm --version	=> hhvm 3.18.1
## nginx -v		=> nginx 1.11.9
## ============================================

## Remove no longer required packages and clean up apt
sudo apt-get autoremove --assume-yes
sudo apt-get clean --assume-yes
sudo apt-get autoclean --assume-yes

## Make sure release-upgrade won't block on user-feedback-for-motd-file
echo 'DPkg::options { "--force-confdef"; "--force-confmiss"; }' | sudo tee /etc/apt/apt.conf.d/local

## Upgrade to 16.04 LTS (not using DistUpgradeViewNonInteractive because of lacking console feedback)
sudo sh -c 'echo "y\ny\ny\ny\n" | DEBIAN_FRONTEND=noninteractive /usr/bin/do-release-upgrade'

## Remove temporary motd-workaround again
sudo rm /etc/apt/apt.conf.d/local

## Cakebox specific: remove unused nginx site and motd message
sudo rm /etc/nginx/sites-available/default.dpkg-dist
sudo rm /etc/update-motd.d/10-help-text

## All done, after vm reboot (optional, `vagrant reload`)
## the new kernel should be active (4.4.0-66)
uname -r
```

**Comment by bravo-kernel** [comment]
### TODO:

- percona upgrade
- php7-fpm

**Comment by bravo-kernel** [comment]
Input needed: any php modules you would like to see added to this current cakebox-installed-list:

```bash
sudo apt-get install php7.1-apc --assume-yes
sudo apt-get install php7.1-bcmath --assume-yes
sudo apt-get install php7.1-bz2 --assume-yes
sudo apt-get install php7.1-curl --assume-yes
sudo apt-get install php7.1-dba --assume-yes
sudo apt-get install php7.1-dom --assume-yes
sudo apt-get install php7.1-gd --assume-yes
sudo apt-get install php7.1-gearman --assume-yes
sudo apt-get install php7.1-geoip --assume-yes
sudo apt-get install php7.1-gmp --assume-yes
sudo apt-get install php7.1-imagick --assume-yes
sudo apt-get install php7.1-imap --assume-yes
sudo apt-get install php7.1-intl --assume-yes
sudo apt-get install php7.1-json --assume-yes
sudo apt-get install php7.1-mbstring --assume-yes
sudo apt-get install php7.1-mcrypt --assume-yes
sudo apt-get install php7.1-memcache --assume-yes
sudo apt-get install php7.1-memcached --assume-yes
sudo apt-get install php7.1-mysql --assume-yes
sudo apt-get install php7.1-mysqli --assume-yes
sudo apt-get install php7.1-readline --assume-yes
sudo apt-get install php7.1-redis --assume-yes
sudo apt-get install php7.1-soap --assume-yes
sudo apt-get install php7.1-sqlite3 --assume-yes
sudo apt-get install php7.1-xdebug --assume-yes
sudo apt-get install php7.1-xmlwriter --assume-yes
sudo apt-get install php7.1-zip --assume-yes
sudo apt-get install php7.1-zlib --assume-yes
```

**Comment by dereuromark** [comment]
Looks pretty good
What I always have to install (for all the frontend things):

* npm
* nodejs-legacy (maybe not necessary with a newer release)

**Comment by bravo-kernel** [comment]
Right, I might just pop node in there as well (if it's not too complicated).

**Comment by bravo-kernel** [comment]
node's in there too, see the todo-list

**Comment by bravo-kernel** [comment]
Assistance appreciated as I seem to be a bit in a bit of a race-condition pickle here after upgrading to php 7.1.

Seems [CakeboxExecute.php](https://github.com/alt3/cakebox-console/blob/7443bd1b728449e5e71828e06609e990a65d76ca/src/Lib/CakeboxExecute.php) still makes heavy use of conflicting Cake\Utility\String breaking vagrant provisioning;

```bash
==> default: PHP Fatal error:  Cannot use Cake\Utility\String as String because String' is a special class name in /cakebox/console/src/Lib/CakeboxExecute.php on line 11
 ```

**Comment by dereuromark** [comment]
Those should directly be replacable with Text:: calls I would say.

**Comment by bravo-kernel** [comment]
Let me see if updating the console prior to upgrading solves things, thanks

**Comment by bravo-kernel** [comment]
I just upgraded my production vm using the merged upgrade script. Due to the complexity of the upgrade I chose to :

- not integrate it with the vagrant provisioning (giving user a choice to stay on old/PHP5.6)
- use the login message to detect non-16.04 boxes
- warn users of outdated boxes
- advize them to run `/cakebox/bash/ubuntu-16.sh` to perform the in-box upgrade

### Upgrade instructions:

1. on your local machne:
    - create a vagrant snapshot of the current box by running `vagrant snapshot push`
    - update the cakebox repo by running `git pull`
    - install PHP7 compatible cakebox-console by running `vagrant reload --provision`
2. log in to the box:
   - start the in-box upgrade by running `/cakebox/bash/ubuntu-16.sh`
   - after completion log-out
3. on your local machine:
    - reboot the box to complete the upgrade-process by running `vagrant reload`

### Worst-case 

If things go wrong simply restore the pre-upgrade state of your box by running ``vagrant snapshot pop` on your local machine.

**Comment by bravo-kernel** [comment]
Feel free to test. BTW I updated the cakebox-console repo to CakePHP 3.4 so there might be some bugs in the dashboard and application. Fixes would be welcome. E.g.

![afbeelding](https://cloud.githubusercontent.com/assets/230500/24137378/c2afdbde-0e13-11e7-89a3-ca18c12f5d80.png)

**Comment by bravo-kernel** [comment]
Confirmation that the daily backups are functioning as expected would be welcome too: #76
